/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'msanghvi' at '03/09/16 11:20' with Gradle 3.0
 *
 * @author msanghvi, @date 03/09/16 11:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
